export const stringsToSpeak = [
    "Hello, Tell me about yourself.",
    "Well! Lets start without wasting time.",
    "What is JavaScript",
    "What is closure in JavaScript?",
    "Explain the event bubbling and event capturing in JavaScript.",
    "What is the difference between 'undefined' and 'null' in JavaScript?",
    "Explain the difference between '==' and '===' operators in JavaScript.",
    "What is the difference between 'let', 'var', and 'const' in JavaScript?",
    "What is the 'this' keyword in JavaScript and how does it work?",
    "Explain the concept of prototypal inheritance in JavaScript.",
    "What are higher-order functions in JavaScript?",
    "What is the event loop in JavaScript and how does it work?",
    "Explain the difference between 'map', 'filter', and 'reduce' functions in JavaScript.",
    "What is a promise in JavaScript?",
    "Explain the differences between 'async/await' and promises.",
    "What is the 'use strict' directive in JavaScript?",
    "What are the different ways to define a function in JavaScript?",
    "Explain hoisting in JavaScript.",
    "What is the difference between 'call', 'apply', and 'bind' methods in JavaScript?",
    "What are the different data types in JavaScript?",
    "What is scope in JavaScript?",
    "What is the difference between '==', '===', '>', and '>=', operators in JavaScript?",
    "What is the purpose of 'setTimeout' and 'setInterval' functions in JavaScript?",
    // Additional questions:
    "What is the difference between 'slice' and 'splice' in JavaScript?",
    "Explain 'typeof' operator in JavaScript.",
    "What is a closure and how is it used?",
    "What are the different ways to create objects in JavaScript?",
    "Explain the 'prototype' property in JavaScript.",
    "What is an immediately-invoked function expression (IIFE) in JavaScript?",
    "What is event delegation in JavaScript?",
    "Explain the difference between 'var', 'let', and 'const' in terms of scope.",
    "What are JavaScript promises and how do they work?",
    "What is a pure function in JavaScript?",
    "What is memoization in JavaScript?",
    "What is the difference between '==', '===', '!==', and '!=', operators in JavaScript?",
    "What is a JavaScript module?",
    "What is destructuring assignment in JavaScript?",
    "What is the 'new' keyword used for in JavaScript?",
    "Explain the concept of currying in JavaScript.",
    "What is the 'spread' operator in JavaScript?",
    "Explain the concept of 'event bubbling' and 'event capturing'.",
    "What is the difference between 'map' and 'forEach' methods?",
    "What is the 'use strict' mode and why is it used?",
    "What is the purpose of the 'NaN' value in JavaScript?",
    "What is a callback function in JavaScript?",
    "What is the difference between 'var' and 'let'?",
    "What is lexical scope in JavaScript?",
    "What are closures in JavaScript? Provide an example.",
    "What are the differences between 'function declaration' and 'function expression'?",
    "Explain 'Object.keys()' method in JavaScript.",
    "What is the difference between 'delete' and 'undefined' in JavaScript?",
    "What is a 'constructor' in JavaScript?",
    "What is a 'prototype' in JavaScript?",
    "What is the 'arguments' object in JavaScript and how is it used?",
    "What is the 'callstack' in JavaScript?",
    "What is the 'event loop' in JavaScript?",
    "What is 'prototype inheritance' in JavaScript?",
    "What is the difference between 'map' and 'filter' methods in JavaScript?",
    "What is a 'pure function' in JavaScript?",
    "What are the different types of errors in JavaScript?",
    "What is the difference between 'null' and 'undefined' in JavaScript?",
    "What is the 'rest parameter' in JavaScript?",
    "What is 'string interpolation' in JavaScript?",
    "What are 'primitive' and 'non-primitive' data types in JavaScript?",
    "Explain 'async' and 'await' in JavaScript.",
    "What is 'default parameter' in JavaScript?",
    "What is 'lexical scope' in JavaScript?",
    "What is 'arrow function' in JavaScript?",
    "What is the 'prototype chain' in JavaScript?",
    "What is the 'typeof' operator in JavaScript and how does it work?",
    "What is a 'symbol' in JavaScript?",
    "What is the 'let' keyword in JavaScript?",
    "What are 'getter' and 'setter' in JavaScript?",
    "What is the 'event delegation' in JavaScript?",
    "What is 'hoisting' in JavaScript?",
    "What is the 'rest/spread operator' in JavaScript?",
    "What is 'destructuring' in JavaScript?",
    "What is 'call' and 'apply' in JavaScript?",
    "What is 'event loop' in JavaScript?",
    "What is 'scope' in JavaScript?",
    "What is 'DOM' in JavaScript?",
    "What is 'type coercion' in JavaScript?",
    "What is 'prototype' in JavaScript?",
    "What is 'closure' in JavaScript?",
    "What is 'IIFE' in JavaScript?",
    "What is 'callback' in JavaScript?",
    "What is 'memoization' in JavaScript?",
    "What is 'this' keyword in JavaScript?",
    "What is 'let' and 'const' in JavaScript?",
    "What is 'promise' in JavaScript?",
    "What is 'async' and 'await' in JavaScript?",
    "What is 'arrow function' in JavaScript?",
    "What is 'spread operator' in JavaScript?",
    "What is 'template literals' in JavaScript?",
    "What is 'destructuring' in JavaScript?",
    "What is 'variable hoisting' in JavaScript?",
    "What is 'strict mode' in JavaScript?",
    "What is 'event bubbling' in JavaScript?",
    "What is 'event capturing' in JavaScript?",
    "What is 'local storage' in JavaScript?",
    "What is 'session storage' in JavaScript?",
    "What is 'cookie' in JavaScript?",
    "What is 'prototype inheritance' in JavaScript?",
    "What is 'prototype chain' in JavaScript?",
    "What is 'Object.create()' in JavaScript?",
    "What is 'Function.prototype.bind()' in JavaScript?",
    "What is 'Function.prototype.call()' in JavaScript?",
    "What is 'Function.prototype.apply()' in JavaScript?",
    "What is 'Array.prototype.map()' in JavaScript?",
    "What is 'Array.prototype.filter()' in JavaScript?",
    "What is 'Array.prototype.reduce()' in JavaScript?",
    "What is 'Array.prototype.forEach()' in JavaScript?",
    "What is 'Array.prototype.slice()' in JavaScript?",
    "What is 'Array.prototype.splice()' in JavaScript?",
];
